// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package host represents the imported interface "ezbar:plugin/host@0.1.0".
//
// ── host services the guest may import (RFC 0006 §3) ────────────────────────
// Each gated host call is ONLY added to the linker when its capability was
// granted; an ungranted call is absent, not a checked no-op (RFC 0006 §5).
// Long-running calls (http/read-file) are async on the host and carry their own
// timeout — epoch does not fire while a guest is parked in a host future.
package host

import (
	"github.com/birdayz/ezbar/go/internal/ezbar/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Paint represents the type alias "ezbar:plugin/host@0.1.0#paint".
//
// See [types.Paint] for more information.
type Paint = types.Paint

// FeedKind represents the type alias "ezbar:plugin/host@0.1.0#feed-kind".
//
// See [types.FeedKind] for more information.
type FeedKind = types.FeedKind

// EventKind represents the type alias "ezbar:plugin/host@0.1.0#event-kind".
//
// See [types.EventKind] for more information.
type EventKind = types.EventKind

// Log represents the imported function "log".
//
// always available
//
//	log: func(msg: string)
//
//go:nosplit
func Log(msg string) {
	msg0, msg1 := cm.LowerString(msg)
	wasmimport_Log((*uint8)(msg0), (uint32)(msg1))
	return
}

// TextSize represents the imported function "text-size".
//
//	text-size: func() -> f32
//
//go:nosplit
func TextSize() (result float32) {
	result0 := wasmimport_TextSize()
	result = (float32)((float32)(result0))
	return
}

// Fg represents the imported function "fg".
//
//	fg: func() -> paint
//
//go:nosplit
func Fg() (result Paint) {
	wasmimport_Fg(&result)
	return
}

// SetTimeout represents the imported function "set-timeout".
//
//	set-timeout: func(ms: u32)
//
//go:nosplit
func SetTimeout(ms uint32) {
	ms0 := (uint32)(ms)
	wasmimport_SetTimeout((uint32)(ms0))
	return
}

// Subscribe represents the imported function "subscribe".
//
//	subscribe: func(kinds: list<event-kind>)
//
//go:nosplit
func Subscribe(kinds cm.List[EventKind]) {
	kinds0, kinds1 := cm.LowerList(kinds)
	wasmimport_Subscribe((*EventKind)(kinds0), (uint32)(kinds1))
	return
}

// HTTPGet represents the imported function "http-get".
//
// gated by `network { host }`
//
//	http-get: func(url: string) -> result<list<u8>, string>
//
//go:nosplit
func HTTPGet(url string) (result cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	url0, url1 := cm.LowerString(url)
	wasmimport_HTTPGet((*uint8)(url0), (uint32)(url1), &result)
	return
}

// ReadFile represents the imported function "read-file".
//
// gated by `read-file { path }`
//
//	read-file: func(path: string) -> result<list<u8>, string>
//
//go:nosplit
func ReadFile(path string) (result cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	path0, path1 := cm.LowerString(path)
	wasmimport_ReadFile((*uint8)(path0), (uint32)(path1), &result)
	return
}

// FeedSubscribe represents the imported function "feed-subscribe".
//
// gated by `bar-state { feeds }` — one host timer fans out to all subscribers
//
//	feed-subscribe: func(feed: feed-kind, min-period-ms: u32)
//
//go:nosplit
func FeedSubscribe(feed FeedKind, minPeriodMs uint32) {
	feed0 := (uint32)(feed)
	minPeriodMs0 := (uint32)(minPeriodMs)
	wasmimport_FeedSubscribe((uint32)(feed0), (uint32)(minPeriodMs0))
	return
}
