// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "ezbar:plugin@0.1.0".

//go:wasmimport ezbar:plugin/host@0.1.0 log
//go:noescape
func wasmimport_Log(msg0 *uint8, msg1 uint32)

//go:wasmimport ezbar:plugin/host@0.1.0 text-size
//go:noescape
func wasmimport_TextSize() (result0 float32)

//go:wasmimport ezbar:plugin/host@0.1.0 fg
//go:noescape
func wasmimport_Fg(result *Paint)

//go:wasmimport ezbar:plugin/host@0.1.0 set-timeout
//go:noescape
func wasmimport_SetTimeout(ms0 uint32)

//go:wasmimport ezbar:plugin/host@0.1.0 subscribe
//go:noescape
func wasmimport_Subscribe(kinds0 *EventKind, kinds1 uint32)

//go:wasmimport ezbar:plugin/host@0.1.0 http-get
//go:noescape
func wasmimport_HTTPGet(url0 *uint8, url1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], string])

//go:wasmimport ezbar:plugin/host@0.1.0 read-file
//go:noescape
func wasmimport_ReadFile(path0 *uint8, path1 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], string])

//go:wasmimport ezbar:plugin/host@0.1.0 feed-subscribe
//go:noescape
func wasmimport_FeedSubscribe(feed0 uint32, minPeriodMs0 uint32)
