// Code generated by wit-bindgen-go. DO NOT EDIT.

package events

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// PointerEventShape is used for storage in variant or result types.
type PointerEventShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(PointerEvent{})]byte
}
