// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package events represents the imported interface "ezbar:plugin/events@0.1.0".
//
// ── events delivered to the guest ───────────────────────────────────────────
package events

import (
	"github.com/birdayz/ezbar/go/internal/ezbar/plugin/types"
	"go.bytecodealliance.org/cm"
)

// FeedKind represents the type alias "ezbar:plugin/events@0.1.0#feed-kind".
//
// See [types.FeedKind] for more information.
type FeedKind = types.FeedKind

// PointerKind represents the enum "ezbar:plugin/events@0.1.0#pointer-kind".
//
//	enum pointer-kind {
//		press,
//		right-press,
//		scroll,
//		enter,
//		leave
//	}
type PointerKind uint8

const (
	PointerKindPress PointerKind = iota
	PointerKindRightPress
	PointerKindScroll
	PointerKindEnter
	PointerKindLeave
)

var _PointerKindStrings = [5]string{
	"press",
	"right-press",
	"scroll",
	"enter",
	"leave",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e PointerKind) String() string {
	return _PointerKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e PointerKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *PointerKind) UnmarshalText(text []byte) error {
	return _PointerKindUnmarshalCase(e, text)
}

var _PointerKindUnmarshalCase = cm.CaseUnmarshaler[PointerKind](_PointerKindStrings[:])

// PointerEvent represents the record "ezbar:plugin/events@0.1.0#pointer-event".
//
//	record pointer-event {
//		id: string,
//		kind: pointer-kind,
//		delta: f32,
//	}
type PointerEvent struct {
	_     cm.HostLayout `json:"-"`
	ID    string        `json:"id"`
	Kind  PointerKind   `json:"kind"`
	Delta float32       `json:"delta"`
}

// FeedSample represents the record "ezbar:plugin/events@0.1.0#feed-sample".
//
//	record feed-sample {
//		feed: feed-kind,
//		value: f64,
//	}
type FeedSample struct {
	_     cm.HostLayout `json:"-"`
	Feed  FeedKind      `json:"feed"`
	Value float64       `json:"value"`
}

// Event represents the variant "ezbar:plugin/events@0.1.0#event".
//
//	variant event {
//		timer,
//		pointer(pointer-event),
//		feed(feed-sample),
//		config(list<tuple<string, string>>),
//	}
type Event cm.Variant[uint8, PointerEventShape, FeedSample]

// EventTimer returns a [Event] of case "timer".
func EventTimer() Event {
	var data struct{}
	return cm.New[Event](0, data)
}

// Timer returns true if [Event] represents the variant case "timer".
func (self *Event) Timer() bool {
	return self.Tag() == 0
}

// EventPointer returns a [Event] of case "pointer".
func EventPointer(data PointerEvent) Event {
	return cm.New[Event](1, data)
}

// Pointer returns a non-nil *[PointerEvent] if [Event] represents the variant case "pointer".
func (self *Event) Pointer() *PointerEvent {
	return cm.Case[PointerEvent](self, 1)
}

// EventFeed returns a [Event] of case "feed".
func EventFeed(data FeedSample) Event {
	return cm.New[Event](2, data)
}

// Feed returns a non-nil *[FeedSample] if [Event] represents the variant case "feed".
func (self *Event) Feed() *FeedSample {
	return cm.Case[FeedSample](self, 2)
}

// EventConfig returns a [Event] of case "config".
func EventConfig(data cm.List[[2]string]) Event {
	return cm.New[Event](3, data)
}

// Config returns a non-nil *[cm.List[[2]string]] if [Event] represents the variant case "config".
func (self *Event) Config() *cm.List[[2]string] {
	return cm.Case[cm.List[[2]string]](self, 3)
}

var _EventStrings = [4]string{
	"timer",
	"pointer",
	"feed",
	"config",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Event) String() string {
	return _EventStrings[v.Tag()]
}
