// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// Rgba8Shape is used for storage in variant or result types.
type Rgba8Shape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Rgba8{})]byte
}
