// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "ezbar:plugin/types@0.1.0".
//
// ── shared types ──────────────────────────────────────────────────────────
package types

import (
	"go.bytecodealliance.org/cm"
)

// Rgba8 represents the record "ezbar:plugin/types@0.1.0#rgba8".
//
// A colour the host resolves: a semantic theme token, or a literal rgba.
// Plugins describe intent; the host owns the final palette (RFC 0006 §2).
//
//	record rgba8 {
//		r: u8,
//		g: u8,
//		b: u8,
//		a: u8,
//	}
type Rgba8 struct {
	_ cm.HostLayout `json:"-"`
	R uint8         `json:"r"`
	G uint8         `json:"g"`
	B uint8         `json:"b"`
	A uint8         `json:"a"`
}

// ThemeToken represents the enum "ezbar:plugin/types@0.1.0#theme-token".
//
//	enum theme-token {
//		fg,
//		fg-dim,
//		accent,
//		ok,
//		warn,
//		urgent,
//		bg
//	}
type ThemeToken uint8

const (
	ThemeTokenFg ThemeToken = iota
	ThemeTokenFgDim
	ThemeTokenAccent
	ThemeTokenOK
	ThemeTokenWarn
	ThemeTokenUrgent
	ThemeTokenBg
)

var _ThemeTokenStrings = [7]string{
	"fg",
	"fg-dim",
	"accent",
	"ok",
	"warn",
	"urgent",
	"bg",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e ThemeToken) String() string {
	return _ThemeTokenStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e ThemeToken) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *ThemeToken) UnmarshalText(text []byte) error {
	return _ThemeTokenUnmarshalCase(e, text)
}

var _ThemeTokenUnmarshalCase = cm.CaseUnmarshaler[ThemeToken](_ThemeTokenStrings[:])

// Paint represents the variant "ezbar:plugin/types@0.1.0#paint".
//
//	variant paint {
//		token(theme-token),
//		rgba(rgba8),
//	}
type Paint cm.Variant[uint8, Rgba8Shape, Rgba8]

// PaintToken returns a [Paint] of case "token".
func PaintToken(data ThemeToken) Paint {
	return cm.New[Paint](0, data)
}

// Token returns a non-nil *[ThemeToken] if [Paint] represents the variant case "token".
func (self *Paint) Token() *ThemeToken {
	return cm.Case[ThemeToken](self, 0)
}

// PaintRgba returns a [Paint] of case "rgba".
func PaintRgba(data Rgba8) Paint {
	return cm.New[Paint](1, data)
}

// Rgba returns a non-nil *[Rgba8] if [Paint] represents the variant case "rgba".
func (self *Paint) Rgba() *Rgba8 {
	return cm.Case[Rgba8](self, 1)
}

var _PaintStrings = [2]string{
	"token",
	"rgba",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Paint) String() string {
	return _PaintStrings[v.Tag()]
}

// Align represents the enum "ezbar:plugin/types@0.1.0#align".
//
//	enum align {
//		start,
//		center,
//		end
//	}
type Align uint8

const (
	AlignStart Align = iota
	AlignCenter
	AlignEnd
)

var _AlignStrings = [3]string{
	"start",
	"center",
	"end",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Align) String() string {
	return _AlignStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Align) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Align) UnmarshalText(text []byte) error {
	return _AlignUnmarshalCase(e, text)
}

var _AlignUnmarshalCase = cm.CaseUnmarshaler[Align](_AlignStrings[:])

// IconID represents the enum "ezbar:plugin/types@0.1.0#icon-id".
//
// The host-rendered icon set (our embedded SVGs). Extended additively only.
//
//	enum icon-id {
//		cpu,
//		memory,
//		temperature,
//		ping,
//		volume-high,
//		volume-medium,
//		volume-mute,
//		battery,
//		battery-charging,
//		battery-warning,
//		bot,
//		github,
//		spotify,
//		kubernetes,
//		clock,
//		calendar,
//		disk,
//		net,
//		ip,
//		updates,
//		keyboard,
//		cloud,
//		sun,
//		moon,
//		alert,
//		dot,
//		cloud-sun,
//		cloud-moon,
//		cloud-fog,
//		cloud-drizzle,
//		cloud-rain,
//		cloud-rain-wind,
//		cloud-snow,
//		cloud-hail,
//		cloud-lightning,
//		droplets,
//		wind,
//		sunrise,
//		sunset,
//		snowflake
//	}
type IconID uint8

const (
	IconIDCPU IconID = iota
	IconIDMemory
	IconIDTemperature
	IconIDPing
	IconIDVolumeHigh
	IconIDVolumeMedium
	IconIDVolumeMute
	IconIDBattery
	IconIDBatteryCharging
	IconIDBatteryWarning
	IconIDBot
	IconIDGithub
	IconIDSpotify
	IconIDKubernetes
	IconIDClock
	IconIDCalendar
	IconIDDisk
	IconIDNet
	IconIDIP
	IconIDUpdates
	IconIDKeyboard
	IconIDCloud
	IconIDSun
	IconIDMoon
	IconIDAlert
	IconIDDot

	// weather conditions (additive — appended only, never reordered)
	IconIDCloudSun
	IconIDCloudMoon
	IconIDCloudFog
	IconIDCloudDrizzle
	IconIDCloudRain
	IconIDCloudRainWind
	IconIDCloudSnow
	IconIDCloudHail
	IconIDCloudLightning
	IconIDDroplets
	IconIDWind
	IconIDSunrise
	IconIDSunset
	IconIDSnowflake
)

var _IconIDStrings = [40]string{
	"cpu",
	"memory",
	"temperature",
	"ping",
	"volume-high",
	"volume-medium",
	"volume-mute",
	"battery",
	"battery-charging",
	"battery-warning",
	"bot",
	"github",
	"spotify",
	"kubernetes",
	"clock",
	"calendar",
	"disk",
	"net",
	"ip",
	"updates",
	"keyboard",
	"cloud",
	"sun",
	"moon",
	"alert",
	"dot",
	"cloud-sun",
	"cloud-moon",
	"cloud-fog",
	"cloud-drizzle",
	"cloud-rain",
	"cloud-rain-wind",
	"cloud-snow",
	"cloud-hail",
	"cloud-lightning",
	"droplets",
	"wind",
	"sunrise",
	"sunset",
	"snowflake",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e IconID) String() string {
	return _IconIDStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e IconID) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *IconID) UnmarshalText(text []byte) error {
	return _IconIDUnmarshalCase(e, text)
}

var _IconIDUnmarshalCase = cm.CaseUnmarshaler[IconID](_IconIDStrings[:])

// GraphKind represents the enum "ezbar:plugin/types@0.1.0#graph-kind".
//
//	enum graph-kind {
//		cpu,
//		memory,
//		temperature,
//		ping,
//		generic
//	}
type GraphKind uint8

const (
	GraphKindCPU GraphKind = iota
	GraphKindMemory
	GraphKindTemperature
	GraphKindPing
	GraphKindGeneric
)

var _GraphKindStrings = [5]string{
	"cpu",
	"memory",
	"temperature",
	"ping",
	"generic",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e GraphKind) String() string {
	return _GraphKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e GraphKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *GraphKind) UnmarshalText(text []byte) error {
	return _GraphKindUnmarshalCase(e, text)
}

var _GraphKindUnmarshalCase = cm.CaseUnmarshaler[GraphKind](_GraphKindStrings[:])

// FeedKind represents the enum "ezbar:plugin/types@0.1.0#feed-kind".
//
//	enum feed-kind {
//		cpu,
//		memory,
//		temperature,
//		ping,
//		battery,
//		net
//	}
type FeedKind uint8

const (
	FeedKindCPU FeedKind = iota
	FeedKindMemory
	FeedKindTemperature
	FeedKindPing
	FeedKindBattery
	FeedKindNet
)

var _FeedKindStrings = [6]string{
	"cpu",
	"memory",
	"temperature",
	"ping",
	"battery",
	"net",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e FeedKind) String() string {
	return _FeedKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e FeedKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *FeedKind) UnmarshalText(text []byte) error {
	return _FeedKindUnmarshalCase(e, text)
}

var _FeedKindUnmarshalCase = cm.CaseUnmarshaler[FeedKind](_FeedKindStrings[:])

// EventKind represents the enum "ezbar:plugin/types@0.1.0#event-kind".
//
//	enum event-kind {
//		timer,
//		pointer,
//		feed,
//		config
//	}
type EventKind uint8

const (
	EventKindTimer EventKind = iota
	EventKindPointer
	EventKindFeed
	EventKindConfig
)

var _EventKindStrings = [4]string{
	"timer",
	"pointer",
	"feed",
	"config",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e EventKind) String() string {
	return _EventKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e EventKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *EventKind) UnmarshalText(text []byte) error {
	return _EventKindUnmarshalCase(e, text)
}

var _EventKindUnmarshalCase = cm.CaseUnmarshaler[EventKind](_EventKindStrings[:])
