// Code generated by wit-bindgen-go. DO NOT EDIT.

package ui

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TextNodeShape is used for storage in variant or result types.
type TextNodeShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TextNode{})]byte
}
