// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package ui represents the imported interface "ezbar:plugin/ui@0.1.0".
//
// ── the bounded widget vocabulary (RFC 0006 §2/§2a) ─────────────────────────
// NOT arbitrary iced: no canvas/shader/custom widgets. The host renders this
// with real iced and enforces a node-count + depth cap incrementally during the
// lift (RFC 0006 §1a/v2.1).
package ui

import (
	"github.com/birdayz/ezbar/go/internal/ezbar/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Paint represents the type alias "ezbar:plugin/ui@0.1.0#paint".
//
// See [types.Paint] for more information.
type Paint = types.Paint

// Align represents the type alias "ezbar:plugin/ui@0.1.0#align".
//
// See [types.Align] for more information.
type Align = types.Align

// IconID represents the type alias "ezbar:plugin/ui@0.1.0#icon-id".
//
// See [types.IconID] for more information.
type IconID = types.IconID

// GraphKind represents the type alias "ezbar:plugin/ui@0.1.0#graph-kind".
//
// See [types.GraphKind] for more information.
type GraphKind = types.GraphKind

// TextNode represents the record "ezbar:plugin/ui@0.1.0#text-node".
//
//	record text-node {
//		content: string,
//		color: paint,
//		size: option<f32>,
//	}
type TextNode struct {
	_       cm.HostLayout      `json:"-"`
	Content string             `json:"content"`
	Color   Paint              `json:"color"`
	Size    cm.Option[float32] `json:"size"`
}

// IconNode represents the record "ezbar:plugin/ui@0.1.0#icon-node".
//
//	record icon-node {
//		id: icon-id,
//		color: paint,
//		size: f32,
//	}
type IconNode struct {
	_     cm.HostLayout `json:"-"`
	ID    IconID        `json:"id"`
	Color Paint         `json:"color"`
	Size  float32       `json:"size"`
}

// GraphNode represents the record "ezbar:plugin/ui@0.1.0#graph-node".
//
//	record graph-node {
//		values: list<f64>,
//		kind: graph-kind,
//		line: paint,
//	}
type GraphNode struct {
	_      cm.HostLayout    `json:"-"`
	Values cm.List[float64] `json:"values"`
	Kind   GraphKind        `json:"kind"`
	Line   Paint            `json:"line"`
}

// ChartNode represents the record "ezbar:plugin/ui@0.1.0#chart-node".
//
// a high-fidelity smoothed gradient area chart (the stock-popup renderer)
//
//	record chart-node {
//		values: list<f64>,
//		line: paint,
//		width: f32,
//		height: f32,
//	}
type ChartNode struct {
	_      cm.HostLayout    `json:"-"`
	Values cm.List[float64] `json:"values"`
	Line   Paint            `json:"line"`
	Width  float32          `json:"width"`
	Height float32          `json:"height"`
}

// LayoutNode represents the record "ezbar:plugin/ui@0.1.0#layout-node".
//
// child indices into the flat `nodes` arena of a `tree` (avoids recursive
// WIT variants and makes the host's incremental depth/count cap trivial).
//
//	record layout-node {
//		children: list<u32>,
//		spacing: f32,
//		align: align,
//	}
type LayoutNode struct {
	_        cm.HostLayout   `json:"-"`
	Children cm.List[uint32] `json:"children"`
	Spacing  float32         `json:"spacing"`
	Align    Align           `json:"align"`
}

// BoxNode represents the record "ezbar:plugin/ui@0.1.0#box-node".
//
//	record box-node {
//		child: u32,
//		padding: f32,
//	}
type BoxNode struct {
	_       cm.HostLayout `json:"-"`
	Child   uint32        `json:"child"`
	Padding float32       `json:"padding"`
}

// HitNode represents the record "ezbar:plugin/ui@0.1.0#hit-node".
//
//	record hit-node {
//		child: u32,
//		id: string,
//	}
type HitNode struct {
	_     cm.HostLayout `json:"-"`
	Child uint32        `json:"child"`
	ID    string        `json:"id"`
}

// Node represents the variant "ezbar:plugin/ui@0.1.0#node".
//
//	variant node {
//		text(text-node),
//		row(layout-node),
//		column(layout-node),
//		container(box-node),
//		mouse-area(hit-node),
//		icon(icon-node),
//		graph(graph-node),
//		chart(chart-node),
//		spacer(f32),
//	}
type Node cm.Variant[uint8, TextNodeShape, TextNode]

// NodeText returns a [Node] of case "text".
func NodeText(data TextNode) Node {
	return cm.New[Node](0, data)
}

// Text returns a non-nil *[TextNode] if [Node] represents the variant case "text".
func (self *Node) Text() *TextNode {
	return cm.Case[TextNode](self, 0)
}

// NodeRow returns a [Node] of case "row".
func NodeRow(data LayoutNode) Node {
	return cm.New[Node](1, data)
}

// Row returns a non-nil *[LayoutNode] if [Node] represents the variant case "row".
func (self *Node) Row() *LayoutNode {
	return cm.Case[LayoutNode](self, 1)
}

// NodeColumn returns a [Node] of case "column".
func NodeColumn(data LayoutNode) Node {
	return cm.New[Node](2, data)
}

// Column returns a non-nil *[LayoutNode] if [Node] represents the variant case "column".
func (self *Node) Column() *LayoutNode {
	return cm.Case[LayoutNode](self, 2)
}

// NodeContainer returns a [Node] of case "container".
func NodeContainer(data BoxNode) Node {
	return cm.New[Node](3, data)
}

// Container returns a non-nil *[BoxNode] if [Node] represents the variant case "container".
func (self *Node) Container() *BoxNode {
	return cm.Case[BoxNode](self, 3)
}

// NodeMouseArea returns a [Node] of case "mouse-area".
func NodeMouseArea(data HitNode) Node {
	return cm.New[Node](4, data)
}

// MouseArea returns a non-nil *[HitNode] if [Node] represents the variant case "mouse-area".
func (self *Node) MouseArea() *HitNode {
	return cm.Case[HitNode](self, 4)
}

// NodeIcon returns a [Node] of case "icon".
func NodeIcon(data IconNode) Node {
	return cm.New[Node](5, data)
}

// Icon returns a non-nil *[IconNode] if [Node] represents the variant case "icon".
func (self *Node) Icon() *IconNode {
	return cm.Case[IconNode](self, 5)
}

// NodeGraph returns a [Node] of case "graph".
func NodeGraph(data GraphNode) Node {
	return cm.New[Node](6, data)
}

// Graph returns a non-nil *[GraphNode] if [Node] represents the variant case "graph".
func (self *Node) Graph() *GraphNode {
	return cm.Case[GraphNode](self, 6)
}

// NodeChart returns a [Node] of case "chart".
func NodeChart(data ChartNode) Node {
	return cm.New[Node](7, data)
}

// Chart returns a non-nil *[ChartNode] if [Node] represents the variant case "chart".
func (self *Node) Chart() *ChartNode {
	return cm.Case[ChartNode](self, 7)
}

// NodeSpacer returns a [Node] of case "spacer".
func NodeSpacer(data float32) Node {
	return cm.New[Node](8, data)
}

// Spacer returns a non-nil *[float32] if [Node] represents the variant case "spacer".
func (self *Node) Spacer() *float32 {
	return cm.Case[float32](self, 8)
}

var _NodeStrings = [9]string{
	"text",
	"row",
	"column",
	"container",
	"mouse-area",
	"icon",
	"graph",
	"chart",
	"spacer",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Node) String() string {
	return _NodeStrings[v.Tag()]
}

// Tree represents the record "ezbar:plugin/ui@0.1.0#tree".
//
// A render is a flat arena of nodes; `root` indexes the top node. The host
// walks it iteratively with a hard cap on count and depth.
//
//	record tree {
//		nodes: list<node>,
//		root: u32,
//	}
type Tree struct {
	_     cm.HostLayout `json:"-"`
	Nodes cm.List[Node] `json:"nodes"`
	Root  uint32        `json:"root"`
}
