// Code generated by wit-bindgen-go. DO NOT EDIT.

package plugin

import (
	"github.com/birdayz/ezbar/go/internal/ezbar/plugin/events"
	"github.com/birdayz/ezbar/go/internal/ezbar/plugin/types"
	"go.bytecodealliance.org/cm"
	"strconv"
)

func lift_PointerEvent(f0 *uint8, f1 uint32, f2 uint32, f3 float32) (v events.PointerEvent) {
	v.ID = cm.LiftString[string](f0, f1)
	v.Kind = (events.PointerKind)(f2)
	v.Delta = (float32)(f3)
	return
}

func lift_FeedSample(f0 uint32, f1 float64) (v events.FeedSample) {
	v.Feed = (types.FeedKind)(f0)
	v.Value = (float64)(f1)
	return
}

func lift_Event(f0 uint32, f1 uint32, f2 uint64, f3 uint32, f4 float32) (v events.Event) {
	switch f0 {
	case 0:
		return cm.New[events.Event](0, struct{}{})
	case 1:
		return cm.New[events.Event](1, lift_PointerEvent(cm.U32ToPointer[uint8](f1), (uint32)(f2), (uint32)(f3), (float32)(f4)))
	case 2:
		return cm.New[events.Event](2, lift_FeedSample((uint32)(f1), (float64)(cm.U64ToF64(f2))))
	case 3:
		return cm.New[events.Event](3, cm.LiftList[cm.List[[2]string]](cm.U32ToPointer[[2]string](f1), (uint32)(f2)))
	}
	panic("lift variant: unknown case: " + strconv.Itoa(int(f0)))
}
