// Code generated by wit-bindgen-go. DO NOT EDIT.

package plugin

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "ezbar:plugin/plugin@0.1.0".
var Exports struct {
	// Init represents the caller-defined, exported function "init".
	//
	//	init: func(config: list<tuple<string, string>>)
	Init func(config cm.List[[2]string])

	// Update represents the caller-defined, exported function "update".
	//
	// returns true if the chip needs re-rendering (Zellij's dirty bit)
	//
	//	update: func(ev: event) -> bool
	Update func(ev Event) (result bool)

	// View represents the caller-defined, exported function "view".
	//
	// PURE + synchronous: no host imports, no await. Host-capped during lift.
	//
	//	view: func() -> tree
	View func() (result Tree)

	// Popup represents the caller-defined, exported function "popup".
	//
	//	popup: func() -> option<tree>
	Popup func() (result cm.Option[Tree])

	// SaveState represents the caller-defined, exported function "save-state".
	//
	// state hand-off across a CLEAN reload only (lost on a trap — RFC 0006 §1a)
	//
	//	save-state: func() -> list<u8>
	SaveState func() (result cm.List[uint8])

	// Restore represents the caller-defined, exported function "restore".
	//
	//	restore: func(state: list<u8>)
	Restore func(state cm.List[uint8])
}
