// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package plugin represents the world "ezbar:plugin/plugin@0.1.0".
//
// ── the plugin world ────────────────────────────────────────────────────────
package plugin

import (
	"github.com/birdayz/ezbar/go/internal/ezbar/plugin/events"
	"github.com/birdayz/ezbar/go/internal/ezbar/plugin/ui"
)

// Tree represents the type alias "ezbar:plugin/plugin@0.1.0#tree".
//
// See [ui.Tree] for more information.
type Tree = ui.Tree

// Event represents the type alias "ezbar:plugin/plugin@0.1.0#event".
//
// See [events.Event] for more information.
type Event = events.Event
