// Code generated by wit-bindgen-go. DO NOT EDIT.

package plugin

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "ezbar:plugin@0.1.0".

//go:wasmexport init
//export init
func wasmexport_Init(config0 *[2]string, config1 uint32) {
	config := cm.LiftList[cm.List[[2]string]]((*[2]string)(config0), (uint32)(config1))
	Exports.Init(config)
	return
}

//go:wasmexport update
//export update
func wasmexport_Update(ev0 uint32, ev1 uint32, ev2 uint64, ev3 uint32, ev4 float32) (result0 uint32) {
	ev := lift_Event((uint32)(ev0), (uint32)(ev1), (uint64)(ev2), (uint32)(ev3), (float32)(ev4))
	result := Exports.Update(ev)
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport view
//export view
func wasmexport_View() (result *Tree) {
	result_ := Exports.View()
	result = &result_
	return
}

//go:wasmexport popup
//export popup
func wasmexport_Popup() (result *cm.Option[Tree]) {
	result_ := Exports.Popup()
	result = &result_
	return
}

//go:wasmexport save-state
//export save-state
func wasmexport_SaveState() (result *cm.List[uint8]) {
	result_ := Exports.SaveState()
	result = &result_
	return
}

//go:wasmexport restore
//export restore
func wasmexport_Restore(state0 *uint8, state1 uint32) {
	state := cm.LiftList[cm.List[uint8]]((*uint8)(state0), (uint32)(state1))
	Exports.Restore(state)
	return
}
