name: Build 

on:
  push:
    branches: [ "main" ]
    tags:     [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: read
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write



jobs:
  test-and-build:
    name: Test + Build inside container
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    container:
      image: ghcr.io/birdayz/ezbar:ci-latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # <-- Important: get full git metadata
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: go test ./...
      - name: Build binary
        run: |
             git config --global --add safe.directory $PWD
             go build -o ezbar .
      - name: Upload release binary
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: ./ezbar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
